package chat.hola.com.app.ecom.cart;

public enum CartUiAction {
  MANAGE_ADDRESS, CHANGE_ADDRESS, BILLING_ADDRESS, CONTINUE_SHOPPING, EMPTY_CART, CROSS_CLICK,
  CLEAR, PROMO_CODE, CHANGE_PAYMENT,
   PRESCRIPTION_UPLOAD, DELIVERY_SCHEDULE_CHANGE, CONTACT_LESS_DELIVERY, EXTRA_NOTE,
  LOGIN_RESULT, LOGIN, PAYMENT, ON_SUCCESS, SUB_TOTAL, ENABLE_BACK, DISABLE_BACK
}
